dl_control_node:
  ros__parameters:
    max_steering: 1.57
    max_speed: 0.5
    min_speed: 0.05
    speed_up_factor: 1.2
    slow_down_factor: 0.5
    turn_right_factor: 1.11
    slow_down_duration_sec: 1.0
    speed_up_duration_sec: 1.0
    turn_right_duration_sec: 0.5
    pedestrian_duration_sec: 3.0
    pedestrian_pass_by_duration_sec: 6.0
    control_1_gain: 0.0057
    control_2_gain: 0.0087
    pedestrian_size_threshold: 3000.0
    slow_down_size_threshold: 1000.0
    speed_up_size_threshold: 1000.0
    turn_right_size_threshold: 3200.0
    linear_x_base_speed: 0.55
